<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-02 14:27
=======
# Generated by Django 4.1.1 on 2022-10-02 13:38
>>>>>>> fdc6cc244ecd38e4d0d13c7fd13ca424161fd379

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
=======
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
>>>>>>> fdc6cc244ecd38e4d0d13c7fd13ca424161fd379
                ('keywords', models.CharField(max_length=20)),
            ],
        ),
    ]
