# Generated by Django 4.1.1 on 2022-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='keywords',
            field=models.CharField(max_length=100),
        ),
    ]
