<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-04 08:26
=======
# Generated by Django 4.1.1 on 2022-10-04 08:15
>>>>>>> 1f1ec8b86badeea72f41d8103fd32ffd4dd33c3b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
