# Generated by Django 4.1.1 on 2022-10-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_review_rating'),
        ('main_app', '0010_profile'),
    ]

    operations = [
    ]
