# Generated by Django 4.1.1 on 2022-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_destination_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='address',
            new_name='city',
        ),
    ]
