# Generated by Django 4.1.1 on 2022-10-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_city_destination_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
    ]
